# ============================
# Global scanning service configuration
# ============================
scanner:
  # Current scanning chain type: evm | solana
  chain_type: "evm"

  # Chain name
  chain_name: "ethereum"

  # Scan start block number (0 = latest block)
  start_block: 0

  # Confirm blocks (e.g. EVM finality 12 blocks)
  confirm_blocks: 5

  # Concurrency (concurrent RPC requests)
  concurrency: 4

  # Whether to enable real-time tracking mode (when the latest block is reached, continue to listen)
  realtime: true

  # Node request timeout (seconds)
  timeout_secs: 15

# ============================
# RPC node configuration
# ============================
rpc:
  # Main node RPC address
  url: "https://mainnet.infura.io/v3/YOUR_API_KEY"

  # Node backup list (optional)
  backups:
    - "https://eth.llamarpc.com"
    - "https://rpc.flashbots.net"

# ============================
# Storage layer configuration
# ============================
storage:
  # RocksDB storage base path
  # Actual path will be: {path}/{chain_name}
  # Examples:
  #   - Ethereum: ./data/rocksdb/Ethereum
  #   - BSC: ./data/rocksdb/BSC
  # This allows multiple chains to run concurrently without conflicts
  path: "./data/rocksdb"

  # Whether to enable compression
  compression: true

# ============================
# Logging and monitoring configuration
# ============================
logging:
  level: "info" # Optional: trace, debug, info, warn, error
  to_file: true # Whether to output to file
  path: "./logs"

metrics:
  enable: true
  prometheus_exporter_port: 9100
