# ============================
# Global scanning service configuration
# ============================
scanner:
  # Current scanning chain type: evm | solana
  chain_type: "evm"

  # Chain name
  chain_name: "ethereum"

  # Scan start block number (0 = latest block)
  start_block: 0

  # Confirm blocks (e.g. EVM finality 12 blocks)
  confirm_blocks: 5

  # Concurrency (concurrent RPC requests)
  concurrency: 4

  # Whether to enable real-time tracking mode (when the latest block is reached, continue to listen)
  realtime: true

  # Node request timeout (seconds)
  timeout_secs: 15

  # ============================
  # Cleanup configuration
  # ============================
  
  # Enable automatic cleanup of old block data
  cleanup_enabled: false
  
  # Number of blocks to retain (blocks older than this will be deleted)
  # Example: 10000 means keep the latest 10000 blocks
  # If not set or 0, cleanup will be skipped
  retention_blocks: 10000
  
  # Cleanup interval in seconds (how often to run cleanup)
  # Default: 3600 (1 hour)
  cleanup_interval_secs: 3600
  
  # Batch size for cleanup operations (blocks per batch)
  # Larger batches are faster but use more memory
  # Default: 1000
  cleanup_batch_size: 1000
  
  # Enable cleanup of orphaned data (blocks not referenced by active indexes)
  # This is more resource-intensive as it scans all block data
  # Default: false (disabled)
  cleanup_orphaned_enabled: false

# ============================
# RPC node configuration
# ============================
rpc:
  # Main node RPC address
  url: "https://mainnet.infura.io/v3/YOUR_API_KEY"

  # Node backup list (optional)
  backups:
    - "https://eth.llamarpc.com"
    - "https://rpc.flashbots.net"

# ============================
# Storage layer configuration
# ============================
storage:
  # RocksDB storage base path
  # Actual path will be: {path}/{chain_name}
  # Examples:
  #   - Ethereum: ./data/rocksdb/Ethereum
  #   - BSC: ./data/rocksdb/BSC
  # This allows multiple chains to run concurrently without conflicts
  path: "./data/rocksdb"

  # Whether to enable compression
  compression: true

# ============================
# Logging and monitoring configuration
# ============================
logging:
  level: "info" # Optional: trace, debug, info, warn, error
  to_file: true # Whether to output to file
  path: "./logs"

metrics:
  enable: true
  prometheus_exporter_port: 9100
